#ifndef THREE_ADDR_CODE_H
#define THREE_ADDR_CODE_H

#include "ast.h"
#include <fstream>
#include <string>
#include <map>
#include <iostream>

using namespace std;

class ThreeAddrCodeGenerator {
private:
    ProgramNode* ast_root;
    ofstream& outcode;
    map<string, string> symbol_to_temp;
    int temp_count;
    int label_count;

public:
    ThreeAddrCodeGenerator(ProgramNode* root, ofstream& out)
        : ast_root(root), outcode(out), temp_count(0), label_count(0) {}

    // Helper method to generate temporary variable names
    string get_temp_var() {
        return "t" + to_string(temp_count++);
    }

    // Helper method to generate label names
    string get_label() {
        return "L" + to_string(label_count++);
    }

    // Method to generate code for function declarations
    void generate_func_code(FuncDeclNode* func) {
        outcode << "// Function: " << func->get_name() << endl;

        // Generate code for parameters
        for (auto& param : func->get_params()) {
            outcode << "// Declaration: " << param.first << " " << param.second << endl;
        }

        // Generate code for function body
        BlockNode* body = func->get_body();
        if (body) {
            body->generate_code(outcode, symbol_to_temp, temp_count, label_count);
        }

    }

    // Method to generate code for main function
    void generate_main_code() {

        // Iterate over the declarations in the main function
        // This part should be extended to generate code for declarations
        for (auto& var : ast_root->get_declarations()) {
            outcode << "// Declaration: " << var.first << endl;
            if (var.second == "int") {
                outcode << "int " << var.first << endl;
            } else if (var.second == "float") {
                outcode << "float " << var.first << endl;
            }
        }

        // Now generate the statements in the main block
        for (auto& stmt : ast_root->get_statements()) {
            stmt->generate_code(outcode, symbol_to_temp, temp_count, label_count);
        }

    }

    // Main generate method to output code
    void generate() {
        outcode << "//========== THREE ADDRESS CODE ==========" << endl;
        outcode << "// This code was generated by a two-pass compiler" << endl;
        outcode << "// Format: " << endl;
        outcode << "// - t0, t1, etc. are temporary variables" << endl;
        outcode << "// - L0, L1, etc. are labels for jumps" << endl;
        outcode << "// - Operations follow the three-address code format" << endl;
        outcode << "// Three Address Code" << endl;

        // Generate code for the entire program
        for (auto func : ast_root->get_functions()) {
            generate_func_code(func);
        }

        generate_main_code();  // Always generate code for the main function

        outcode << "//========== END OF CODE ==========" << endl;
    }
};

#endif // THREE_ADDR_CODE_H
